updating 'webhook' to 'postee'
aquasecurity/postee pull request #104
Opened 2021-03-18 17:11 UTC by cpt-redbeard

updating references to postee

2021-03-18 19:50 UTC, jerbia commented on README.md
>  docker build -t postee:latest .
Can you change the image name to aqua-postee? I see that in the run command you aree using aqua-postee.

2021-03-18 19:51 UTC, jerbia requested changes
Can you change the image name in the documentation to "aqua-postee"? I see places where it says "postee"

2021-03-18 20:42 UTC, cpt-redbeard commented
REDME updated with naming convention change.

2021-03-18 21:36 UTC, jerbia requested changes
@cpt-redbeard There were many changes to the readme.md. Please merge it with the new master.

2021-03-23 17:33 UTC, jerbia commented
@cpt-redbeard Seems like you will need to rebase your pull request

2021-03-23 21:58 UTC, cpt-redbeard commented
@jerbia I believe this was resolved with pull/106

2021-04-24 17:55 UTC, closed without merging