Docs: added description of using env. variables
aquasecurity/postee pull request #194
Opened 2021-11-08 10:37 UTC by DmitriyLewen

Issue #189

2021-11-08 12:14 UTC, AndreyLevchenko requested changes

2021-11-08 12:14 UTC, AndreyLevchenko commented on README.md
> +Postee supports to use of environment variables for *Output* fields: **User**, **Password** and **Token**. To use, insert the preffix `$` to environment variable in the field of the configuration fil
please add code snippet with example below

2021-11-09 06:55 UTC, DmitriyLewen commented on README.md
> +Postee supports to use of environment variables for *Output* fields: **User**, **Password** and **Token**. To use, insert the preffix `$` to environment variable in the field of the configuration fil
example added

2021-11-10 09:07 UTC, jerbia approved these changes

2021-11-10 09:07 UTC, merged