Golangci
aquasecurity/postee pull request #212
Opened 2021-12-10 00:37 UTC by krol3

- Adding https://golangci-lint.run/

2021-12-10 08:15 UTC, AndreyLevchenko requested changes

2021-12-10 08:15 UTC, AndreyLevchenko commented on router/router.go
> +			log.Printf("failed to Terminate : %v", err)
"failed to terminate output"

2021-12-10 08:15 UTC, AndreyLevchenko commented on router/parsecfg_test.go
> +		t.Errorf("Error in WriteFile")
add actual error to message

2021-12-10 08:15 UTC, AndreyLevchenko commented on dbservice/sharedcfg_test.go
> +			t.Fatal("error EnsureApiKey")
add actual error message

2021-12-10 08:15 UTC, AndreyLevchenko commented on dbservice/dbparam_test.go
> +					t.Errorf("Can't change the mode dir: %s", baseDir)
add actual error message

2021-12-10 08:15 UTC, AndreyLevchenko commented on webserver/webserver.go
> +			log.Printf("GenerateCertificate error: %s \n", err)
so `%v`, `%w` or `%s` ? :)

2021-12-10 10:47 UTC, krol3 commented on webserver/webserver.go
> +			log.Printf("GenerateCertificate error: %s \n", err)
Do you mean to use first %v.

2021-12-13 06:24 UTC, AndreyLevchenko approved these changes

2021-12-13 06:40 UTC, merged