Main & postee API merge
aquasecurity/postee pull request #263
Opened 2022-02-01 15:36 UTC by elad-da

2022-02-01 19:05 UTC, simar7 commented
Hi - what issue is this addressing?

2022-02-02 05:56 UTC, AndreyLevchenko commented
it allows to use postee as library to send notifications outside:
See example of usage: https://github.com/elad-da/postee/blob/main-api-merge/router/api_integration_test.go
not sure why it's going to dev branch.

2022-02-02 08:01 UTC, elad-da commented
We created a dev branch so we can align with the main branch and keep changing the Postee to match our requirements to work as a library, without risking the main branch.

2022-02-02 12:57 UTC, AndreyLevchenko requested changes

2022-02-02 12:57 UTC, AndreyLevchenko commented on outputs/email.go
> +			if err := smtp.SendMail(mx.Host+":25", nil, from, []string{rcpt}, []byte(message)); err != nil {
it looks like reverting some fix we just made

2022-02-02 21:58 UTC, simar7 requested changes
> We created a dev branch so we can align with the main branch and keep changing the Postee to match our requirements to work as a library, without risking the main branch.

hi @tomyweiss and @elad-da - appreciate your contributions but as a new reviewer & maintainer of Postee I'm unable to understand the scope of this PR. It's very difficult to review such a PR with many conflicts as @AndreyLevchenko mentioned. 

Could you rebase on the latest main branch of Postee and open a new PR? Happy to assist you offline or here if need be. Let us know!

2022-02-03 09:40 UTC, elad-da commented
Hi @simar7, this is a rebase on the main branch of the Postee-Api feature (postee as a library).

2022-02-07 11:43 UTC, AndreyLevchenko approved these changes

2022-02-07 11:44 UTC, merged